version: '3.8'

services:
  analyzer:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=supermarket_data